import type { Metadata } from "next";
import SessionProvider from "../components/SessionProvider";
import LeftSidebar from "../components/leftsidebar";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <body>
          <div>
          <LeftSidebar />
            {children}
          </div>
        </body>
      </SessionProvider>
    </html>
  );
}
